MetalCore/Controllers/ProveedoresController.cs
using SB_Admin.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SB_Admin.Controllers
{
    public class ProveedoresController : Controller
    {
        [HttpGet]
        public ActionResult Consultar()
        {
            try
            {
                //ProveedoresModel ConsultaActividadesDisponibles = new ProveedoresModel();
                if (Session["User"] != null)
                {
                    UsuarioObj user = (UsuarioObj)Session["User"];
                    return View("Consultar",user.listaPermisos);
                }
                return View("Consultar");
                
            }
            catch (Exception)
            {
                return View("../Shared/Error");
            }
        }

        [HttpGet]
        public ActionResult Crear()
        {
            if (Session["User"] != null)
            {
                UsuarioObj user = (UsuarioObj)Session["User"];
                return View(user.listaPermisos);
            }
            return View("Consultar");
        }

        //Modificar 


        


    }

    
}

MetalCore/Controllers/TrabajoController.cs
using SB_Admin.Filters;
using SB_Admin.Models;
using MetalCore.ETL.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SB_Admin.Controllers
{
    public class TrabajoController : Controller
    {
        // GET: Trabajo


        [HttpGet]
        public ActionResult VerTrabajos()
        {


            try
            {
                TrabajoModel model = new TrabajoModel();


                var respuesta = model.VerTrabajos();

                if (Session["User"] != null)
                {

                    var estados = model.ConsultarEstadosCombo();



                    ViewBag.listaEstados = estados;
                    ViewBag.listaTrabajos = respuesta;


                    return View();
                }
                return View("VerTrabajos");
            }
            catch (Exception)
            {

                return View("VerTrabajos");

            }
        }


        [HttpPost]
        public ActionResult idEspecifico(int IdEstado)
        {
            List<TrabajoObj> lst;
            TrabajoModel model = new TrabajoModel();

            lst = model.ConsultarEstadoEspecifico(IdEstado);



            return Json(lst, JsonRequestBehavior.AllowGet);
        }

        ////////////////////////////////////////////////////


        [HttpGet]
        public ActionResult Consultar()
        {
            UsuarioObj user = (UsuarioObj)Session["User"];
            var token = user.TokenJWT;
            try
            {
                if (Session["User"] != null)
                {

                    TrabajoModel CosultaTrabajos = new TrabajoModel();
                    ViewBag.listaPermisos = user.listaPermisos;
                    var respuesta = CosultaTrabajos.Consultar(token);


                    return View(respuesta);

                }
                return View();

            }
            catch (Exception)
            {
                return View("../Shared/Error");
            }
        }

        [HttpGet]
        public ActionResult ConsultarAsigMateri()
        {
            UsuarioObj user = (UsuarioObj)Session["User"];
            var token = user.TokenJWT;
            try
            {
                if (Session["User"] != null)
                {

                    TrabajoModel ConsultarAsigMateri = new TrabajoModel();
                    ViewBag.listaPermisos = user.listaPermisos;
                    var respuesta = ConsultarAsigMateri.ConsultarAsigMateri(token);


                    return View(respuesta);

                }
                return View();

            }
            catch (Exception)
            {
                return View("../Shared/Error");
            }
        }
        [HttpPost]
        //encontrar precio producto
        public ActionResult EncontrarPrecio(int idProducto)
        {
            UsuarioObj user = (UsuarioObj)Session["User"];
            var token = user.TokenJWT;
            try
            {
                TrabajoModel modeloza = new TrabajoModel();
                ViewBag.listaPermisos = user.listaPermisos;
                var respuesta = modeloza.EncontrarPrecio(idProducto);
                decimal cantidadProducto = respuesta.Precio;
                return Json(cantidadProducto, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return View("../Shared/Error");
            }
        }

        [HttpGet]
        public ActionResult AsignarTrabajoFrm()
        {

            TrabajoModel modelo = new TrabajoModel();
            try
            {

                if (Session["User"] != null)
                {
                    UsuarioObj user = (UsuarioObj)Session["User"];
                    ViewBag.listaPermisos = user.listaPermisos;
                    ViewBag.listaEstados = modelo.ConsultarEstadoTrabajosCombo();
                    TrabajoModel modelos = new TrabajoModel();
                    ViewBag.listaUsuarios = modelos.ConsultarEmpleadoCombo();
                    TrabajoModel modeloza = new TrabajoModel();
                    ViewBag.listaprodu = modeloza.ConsultarProductoCombo();
                    TrabajoModel modelozas = new TrabajoModel();
                    ViewBag.listaTrabajos = modelozas.ConsultarTrabajosCombo();

                }
                return View("Asignar");

            }
            catch (Exception)
            {
                return View("../Shared/Error");
            }
        }

        //asignar materiales
        [HttpGet]
        public ActionResult AsignarMaterialesFrm()
        {

            TrabajoModel modelo = new TrabajoModel();
            try
            {

                if (Session["User"] != null)
                {
                    UsuarioObj user = (UsuarioObj)Session["User"];
                    ViewBag.listaPermisos = user.listaPermisos;

                    TrabajoModel modeloza = new TrabajoModel();
                    ViewBag.listaprodu = modeloza.ConsultarProductoCombo();
                    TrabajoModel modelozas = new TrabajoModel();
                    ViewBag.listaTrabajos = modelozas.ConsultarTrabajosCombo();

                }
                return View("Asignar");

            }
            catch (Exception)
            {
                return View("../Shared/Error");
            }
        }

        //guardar materiales
        [HttpPost]
        public ActionResult AsignarMateriales(MaterialesOBJ trabajo)
        {
            UsuarioObj user = (UsuarioObj)Session["User"];

            int Cantidad = trabajo.Cantidad;
            int idProducto = trabajo.IdProducto;
            try
            {
                TrabajoModel modelo = new TrabajoModel();

                var respuestaV = modelo.VerifiStock(Cantidad, idProducto);
                ViewBag.listaPermisos = user.listaPermisos;


                //validacion
                if (ModelState.IsValid)
                {


                    if (respuestaV == false)
                    {
                        TrabajoModel modelao = new TrabajoModel();
                        ViewBag.listaPermisos = user.listaPermisos;

                        ViewBag.MjsCrearMate = "Mensaje";

                        //TrabajoModel modeloza = new TrabajoModel();
                        //ViewBag.listaEstados = modelo.ConsultarEstadoTrabajosCombo();
                        TrabajoModel modelos = new TrabajoModel();
                        ViewBag.listaUsuarios = modelos.ConsultarEmpleadoCombo();
                        TrabajoModel modelozsa = new TrabajoModel();
                        ViewBag.listaprodu = modelozsa.ConsultarProductoCombo();
                        TrabajoModel modelozas = new TrabajoModel();
                        ViewBag.listaTrabajos = modelozas.ConsultarTrabajosCombo();
                        return View("Asignar");

                    }
                    else
                    {

                        TrabajoModel modelao = new TrabajoModel();
                        ViewBag.listaPermisos = user.listaPermisos;
                        modelao.RegistrarMaterial(trabajo);
                        ViewBag.MjsCreadoMate = "Mensaje";
                        //TrabajoModel modeloza = new TrabajoModel();
                        //ViewBag.listaEstados = modelo.ConsultarEstadoTrabajosCombo();
                        TrabajoModel modelos = new TrabajoModel();
                        ViewBag.listaUsuarios = modelos.ConsultarEmpleadoCombo();
                        TrabajoModel modelozsa = new TrabajoModel();
                        ViewBag.listaprodu = modelozsa.ConsultarProductoCombo();
                        TrabajoModel modelozas = new TrabajoModel();
                        ViewBag.listaTrabajos = modelozas.ConsultarTrabajosCombo();

                        return View("Asignar");
                    }

                }


                return View(trabajo);
            }
            catch (Exception)
            {
                return View("../Shared/Error");
            }
        }


        //guardar trabajos
        [HttpPost]
        public ActionResult RegistrarTrabajo(TrabajoObj trabajo)
        {
            UsuarioObj user = (UsuarioObj)Session["User"];

            int idUsuario = trabajo.IdUsuario; //variables para la validación de existencia
            DateTime fecha = trabajo.Fecha;
            int idTrabajo = trabajo.IdTrabajo;


            try
            {
                TrabajoModel modelo = new TrabajoModel();

                var respuestaV = modelo.VerifiFecha(idUsuario, fecha);//metodo de existencia
                ViewBag.listaPermisos = user.listaPermisos;


                //validacion
                if (ModelState.IsValid)
                {

                    //crea un empleado nuevo
                    if (respuestaV == false)
                    {

                        ViewBag.listaPermisos = user.listaPermisos;

                        ViewBag.MjsCrear = "Mensaje";
                        //TrabajoModel modelaos = new TrabajoModel();
                        //ViewBag.listaEstados = modelaos.ConsultarEstadoTrabajosCombo();
                        TrabajoModel modelos = new TrabajoModel();
                        ViewBag.listaUsuarios = modelos.ConsultarEmpleadoCombo();
                        TrabajoModel modelozsa = new TrabajoModel();
                        ViewBag.listaprodu = modelozsa.ConsultarProductoCombo();
                        TrabajoModel modelozas = new TrabajoModel();
                        ViewBag.listaTrabajos = modelozas.ConsultarTrabajosCombo();
                        return View("Asignar");

                    }
                    else
                    {
                        //crea un empleado nuevo

                        TrabajoModel modelao = new TrabajoModel();
                        ViewBag.listaPermisos = user.listaPermisos;

MetalCore/Views/Shared/_Layout.cshtml
@{
    List<MetalCore.ETL.Entities.PermisosObj> listaPermisos = ViewBag.listaPermisos;
    
}



<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <!--<title>@ViewBag | SB Admin 2 - Dashboard</title>-->
    <title>MetalCore</title>

    <link href="~/Content/SB-Admin/css/sb-admin-2.min.css" rel="stylesheet" />
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" />
    <link href="~/vendor/bootstrap/scss/bootstrap.min.css" rel="stylesheet" />


</head>
<body>


    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="navbar-nav bg-primary sidebar sidebar-dark accordion" id="accordionSidebar">
            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="@Url.Action("Index", "Home")">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-book-reader"></i>
                </div>
                <div class="sidebar-brand-text mx-3">MetalCore</div>
            </a>
            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Dashboard", "Home")">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard (Pendiente Sprint)</span>
                </a>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider">
            <!-- Heading -->
            <div class="sidebar-heading">
                Gestion
            </div>
            <!-- Nav Item - Pages Collapse Menu -->

            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
                   aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-book"></i>
                    <span>Trabajos (Pendiente Sprint)</span>
                </a>
                <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                     data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">

                        @*@foreach (var item in listaPermisos)
                        {
                            if (item.id == 1)
                            {




                            }
                        }*@
                        <a class="collapse-item" href="@Url.Action("AsignarTrabajoFrm", "Trabajo")">Asignar Trabajos</a>




                        <h6 class="collapse-header">Registrar:</h6>
                        <a class="collapse-item" href="@Url.Action("Consultar", "Trabajo")">Consultar Trabajos</a>
                        <a class="collapse-item" href="@Url.Action("ConsultarAsigMateri", "Trabajo")">Consultar Material Asignado</a>
                        <a class="collapse-item" href="@Url.Action("VerTrabajos", "Trabajo")">Ver Trabajos</a>
                    </div>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                   aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-list"></i>
                    <span>Inventario</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("Consultar", "Inventario")">Consultar</a>
                        <a class="collapse-item" href="@Url.Action("CrearProductoFrm", "Inventario")">Registrar Producto</a>
                    </div>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapse3"
                   aria-expanded="true" aria-controls="collapse3">
                    <i class="fas fa-list"></i>
                    <span>Proveedores (Pendiente Sprint)</span>
                </a>
                <div id="collapse3" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("Consultar", "Proveedores")">Consultar</a>
                        <a class="collapse-item" href="@Url.Action("Crear", "Proveedores")">Registrar Proveedor</a>
                    </div>
                </div>
            </li>
            <!-- Nav Item - Utilities Collapse Menu -->





<li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true"
                   aria-controls="collapsePages">
                    <i class="fas fa-user-friends"></i>
                    <span>Usuarios</span>
                </a>
                <div id="collapsePages" class="collapse" aria-labelledby="headingPages"
                     data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Usuarios:</h6>

                        <a class="collapse-item" href="@Url.Action("Consultar","Usuario")">Usuarios</a>
                        <a class="collapse-item" href="@Url.Action("CrearUsuarioFrm","Usuario")">Crear Usuario</a>

                    </div>
                </div>
            </li>



            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>
                    <!-- Topbar Search -->
                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                 aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                               placeholder="Search for..." aria-label="Search"
                                               aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>
                        <div class="topbar-divider d-none d-sm-block"></div>
                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Salir</span>
                                <i class="fas fa-user-shield" style="font-size:25px;font-weight:bold"></i>
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="@Url.Action("CerrarSesion","Home")">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Cerrar Sesion
                                </a>
                            </div>
                        </li>
                    </ul>
                </nav>



                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    @RenderBody()
                </div>
                <!-- /.container-fluid -->


            </div><!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>MetalCore 2022</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->



        </div>
    </div>
    <!-- SCRIPTS-->
    <!-- Bootstrap core JavaScript-->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Content/SB-Admin/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/vendor/chart.js/Chart.js"></script>
    <!-- Page level custom scripts -->
    <script src="~/Content/SB-Admin/js/demo/chart-area-demo.js"></script>
    <script src="~/Content/SB-Admin/js/demo/chart-pie-demo.js"></script>

    <!-- Page level plugins -->
    <script src="~/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/Content/SB-Admin/js/demo/datatables-demo.js"></script>

    <script src="~/Scripts/Funciones/Funciones.js"></script>

    <script src="~/Scripts/Funciones/Trabajo.js"></script>

    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/Funciones/Inventario.js"></script>
    <script src="~/Scripts/Funciones/boton.js"></script>
</body>
</html>